com.tua:
  jwt:
    secret: secret

spring:
  datasource:
    url: jdbc:postgresql://ec2-63-32-248-14.eu-west-1.compute.amazonaws.com:5432/df16fg2103pqle
    username: vmhidospvuiaid
    password: e9ddd8b51b5a1c88bc1b4ef767cc9e8659f1f12ce592dc3751d8c2b93791ccee
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format-sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    open-in-view: false
  jackson:
    time-zone: 'GMT+1'
    serialization:
      fail-on-empty-beans: false

server:
  port: 8089
  servlet:
    context-path: /api/tua
    session:
      cookie:
        name: TUARRESOURCESESSION

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
  server:
    base-path: ${server.servlet.context-path}/actuator

logging:
  level:
    root: info